# Generated by Django 4.2.6 on 2024-03-28 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_elecotorines', '0003_alter_smart_elecotorinesproductadd_image'),
        ('sound_equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='soundSpeckerProductAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='sound_equipment/media/image')),
                ('SoundAndEquipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sound_equipment.soundandequipment')),
                ('productBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_elecotorines.productbrand')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sound_equipment.speaker')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
