# Generated by Django 4.2.6 on 2024-04-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smart_elecotorines', '0006_smartdescriptionmodel_smartspecificaionmodel_and_more'),
        ('sound_equipment', '0003_soundspeckerproductadd_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='soundDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phone_and_tablet/media/image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='soundSpecificaionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ChargingInterface', models.CharField(max_length=350)),
                ('Bluetooth', models.CharField(max_length=350)),
                ('StorageCapacity', models.CharField(max_length=350)),
                ('StorageType', models.CharField(max_length=350)),
                ('GraphicsModel', models.CharField(max_length=350)),
                ('Model', models.CharField(max_length=350)),
                ('Batterycapacity', models.CharField(max_length=350)),
                ('ANCStatus', models.CharField(max_length=350)),
                ('MicStatus', models.CharField(max_length=350)),
                ('DriverSize', models.CharField(blank=True, max_length=350, null=True)),
                ('SweatWaterResistance', models.CharField(blank=True, max_length=350, null=True)),
                ('WirelessCharging', models.CharField(max_length=350)),
                ('Playtime', models.CharField(max_length=350)),
                ('OtherFeaturesInfo', models.CharField(max_length=350)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smart_elecotorines.productbrand')),
            ],
        ),
        migrations.AddField(
            model_name='soundspeckerproductadd',
            name='soundDescriptionModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sound_equipment.sounddescriptionmodel'),
        ),
        migrations.AddField(
            model_name='soundspeckerproductadd',
            name='soundSpecificaionModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sound_equipment.soundspecificaionmodel'),
        ),
    ]
