# Generated by Django 4.2.6 on 2024-04-25 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bennersection',
            name='image',
            field=models.ImageField(upload_to='all_product/up_load/media'),
        ),
    ]
