# Generated by Django 4.2.6 on 2024-04-25 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_product', '0002_alter_bennersection_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BennerSection',
        ),
    ]
