# Generated by Django 4.2.6 on 2024-03-23 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conver_and_glass', '0006_coverandglassproduct_productbrand'),
        ('peripheries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='laptob_and_destop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='loptob_and_desktop/media/image')),
                ('ProductBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conver_and_glass.productbrand')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
