# Generated by Django 4.2.6 on 2024-03-27 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('peripheries', '0004_rename_peripheries_peripheriesproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='peripheriesproduct',
            name='Perpheries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='peripheries.perpheries'),
        ),
    ]
