# Generated by Django 4.2.6 on 2024-04-16 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('peripheries', '0006_peripheriesproduct_quentity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peripheriesproduct',
            old_name='ProductBrand',
            new_name='productBrandModel',
        ),
    ]
