# Generated by Django 4.2.6 on 2024-04-25 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_of_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bennersection',
            name='image',
            field=models.ImageField(upload_to='some_of_product/media/images'),
        ),
    ]
