# Generated by Django 4.2.6 on 2024-04-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_of_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_product',
            name='image',
            field=models.ImageField(upload_to='some_of_product/media/feature_product/'),
        ),
        migrations.AlterField(
            model_name='featured_category',
            name='image',
            field=models.ImageField(upload_to='some_of_product/media/featured_category/'),
        ),
        migrations.AlterField(
            model_name='readyoforder',
            name='image',
            field=models.ImageField(upload_to='some_of_product/media/ReadyOfOrder/'),
        ),
    ]
