# Generated by Django 4.2.6 on 2024-04-26 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_of_product', '0002_alter_bennersection_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='feature_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='some_of_product/media/images')),
            ],
        ),
        migrations.CreateModel(
            name='featured_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='some_of_product/media/images')),
            ],
        ),
        migrations.CreateModel(
            name='ReadyOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('image', models.ImageField(upload_to='some_of_product/media/images')),
            ],
        ),
    ]
