# Generated by Django 4.2.6 on 2024-04-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_of_product', '0003_alter_bennersection_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature_product',
            name='image',
            field=models.ImageField(upload_to='some_of_product/media/image/'),
        ),
    ]
