# Generated by Django 4.2.6 on 2024-04-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_of_product', '0004_alter_feature_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured_category',
            name='image',
            field=models.ImageField(upload_to='some_of_product/media/image/'),
        ),
        migrations.AlterField(
            model_name='readyoforder',
            name='image',
            field=models.ImageField(upload_to='some_of_product/media/image/'),
        ),
    ]
