# Generated by Django 4.2.6 on 2024-04-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('some_of_product', '0006_featureproduct_delete_feature_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadyOfOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='some_of_product/media/image')),
            ],
        ),
    ]
