# Generated by Django 4.2.6 on 2024-04-17 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=250)),
                ('bh', models.CharField(max_length=250)),
                ('count', models.CharField(max_length=250)),
                ('price', models.CharField(max_length=12)),
                ('remarks', models.CharField(max_length=12)),
            ],
        ),
    ]
