# Generated by Django 4.2.6 on 2024-03-24 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_elecotorines', '0002_productbrand_smart_elecotorinesproductadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smart_elecotorinesproductadd',
            name='image',
            field=models.ImageField(upload_to='smart_elecotorines/media/image'),
        ),
    ]
