# Generated by Django 4.2.6 on 2024-04-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_elecotorines', '0003_alter_smart_elecotorinesproductadd_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='smart_elecotorinesproductadd',
            name='quentity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
