# Generated by Django 4.2.6 on 2024-04-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smart_elecotorines', '0006_smartdescriptionmodel_smartspecificaionmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartandelectines',
            options={'verbose_name': 'smartAndelectines', 'verbose_name_plural': 'Smart And electines'},
        ),
        migrations.AlterModelOptions(
            name='smartdescriptionmodel',
            options={'verbose_name': 'Smart Description Model', 'verbose_name_plural': 'Smart Descriptions '},
        ),
        migrations.AlterModelOptions(
            name='smartspecificaionmodel',
            options={'verbose_name': 'Smart Specificaion Model', 'verbose_name_plural': 'Smart Specificaions'},
        ),
    ]
