# Generated by Django 4.2.6 on 2024-04-25 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_elecotorines', '0007_alter_smartandelectines_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartdescriptionmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='smart_elecotorines/media/image'),
        ),
    ]
