# Generated by Django 4.2.6 on 2024-03-23 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_and_tablet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='productBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='laptob_and_destop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='phone_and_tablet/media/image')),
                ('ipadAndTAB', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_and_tablet.ipadandtab')),
                ('phoneAndtablet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_and_tablet.phoneandtablet')),
                ('productBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_and_tablet.productbrand')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
