# Generated by Django 4.2.6 on 2024-03-23 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_and_tablet', '0002_productbrand_laptob_and_destop'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laptob_and_destop',
            new_name='phone_and_tablet',
        ),
    ]
