# Generated by Django 4.2.6 on 2024-03-23 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_and_tablet', '0003_rename_laptob_and_destop_phone_and_tablet'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phone_and_tablet',
            new_name='phone_and_tabletProductadd',
        ),
    ]
