# Generated by Django 4.2.6 on 2024-04-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_and_tablet', '0004_rename_phone_and_tablet_phone_and_tabletproductadd'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone_and_tabletproductadd',
            name='quentity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
