# Generated by Django 4.2.6 on 2024-04-18 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phone_and_tablet', '0006_remove_phone_and_tabletproductadd_quentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=350)),
                ('network', models.CharField(max_length=350)),
                ('Dimensions', models.CharField(max_length=350)),
                ('Weight', models.CharField(max_length=350)),
                ('Sim', models.CharField(max_length=350)),
                ('DisplayType', models.CharField(max_length=350)),
                ('DisplaySize', models.CharField(max_length=350)),
                ('DisplayResolution', models.CharField(max_length=350)),
                ('os', models.CharField(max_length=350)),
                ('Memory', models.CharField(max_length=350)),
                ('MainCemera', models.CharField(max_length=350)),
                ('SelfieCemera', models.CharField(max_length=350)),
                ('Sound', models.CharField(max_length=350)),
                ('BetteryInfo', models.CharField(max_length=350)),
                ('Sensors', models.CharField(max_length=350)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_and_tablet.productbrand')),
            ],
        ),
        migrations.AddField(
            model_name='phone_and_tabletproductadd',
            name='SpecificationModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='phone_and_tablet.specificationmodel'),
        ),
    ]
