# Generated by Django 4.2.6 on 2024-04-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_and_tablet', '0010_alter_phone_and_tabletproductadd_descriptionmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descriptionmodel',
            options={'verbose_name': 'Description Model ', 'verbose_name_plural': ' Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='phone_and_tabletproductadd',
            options={'ordering': ['price'], 'verbose_name': 'Phone and Tablet Product Add', 'verbose_name_plural': 'Phone and Tablet Product Adds'},
        ),
        migrations.AlterModelOptions(
            name='phoneandtablet',
            options={'verbose_name': 'phone And tablet', 'verbose_name_plural': 'phone And Tablet'},
        ),
        migrations.AlterModelOptions(
            name='specificationmodel',
            options={'verbose_name': 'Specification Model  ', 'verbose_name_plural': ' Specifications'},
        ),
    ]
