# Generated by Django 4.2.6 on 2024-03-23 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conver_and_glass', '0006_coverandglassproduct_productbrand'),
        ('fitness_and_wearable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness_and_wearable_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='conver_and_glass/media/image')),
                ('fitnessAndwearable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness_and_wearable.fitnessandwearable')),
                ('productBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conver_and_glass.productbrand')),
                ('watachAndaccessories', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness_and_wearable.watachandaccessories')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
