# Generated by Django 4.2.6 on 2024-03-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_and_wearable', '0002_fitness_and_wearable_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness_and_wearable_product',
            name='image',
            field=models.ImageField(upload_to='fitness_and_wearable/media/image'),
        ),
    ]
