# Generated by Django 4.2.6 on 2024-04-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_and_wearable', '0003_alter_fitness_and_wearable_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness_and_wearable_product',
            name='quentity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
