# Generated by Django 4.2.6 on 2024-04-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conver_and_glass', '0012_remove_coverandglassproduct_quentity_and_more'),
        ('fitness_and_wearable', '0006_remove_fitness_and_wearable_product_quentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phone_and_tablet/media/image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FitnessSpecificaionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=350)),
                ('DisplaySize', models.CharField(max_length=350)),
                ('Compatiblewith', models.CharField(max_length=350)),
                ('OtherFeaturesInfo', models.CharField(max_length=350)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conver_and_glass.productbrandmodel')),
            ],
        ),
        migrations.AddField(
            model_name='fitness_and_wearable_product',
            name='FitnessDescriptionModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness_and_wearable.fitnessdescriptionmodel'),
        ),
        migrations.AddField(
            model_name='fitness_and_wearable_product',
            name='FitnessSpecificaionModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fitness_and_wearable.fitnessspecificaionmodel'),
        ),
    ]
