# Generated by Django 4.2.6 on 2024-04-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_and_wearable', '0007_fitnessdescriptionmodel_fitnessspecificaionmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitness_and_wearable_product',
            options={'ordering': ['price'], 'verbose_name': 'Fitness_and_wearable_Product', 'verbose_name_plural': 'Fitness and wearable Products '},
        ),
        migrations.AlterModelOptions(
            name='fitnessandwearable',
            options={'verbose_name': 'Fitness and Wearable', 'verbose_name_plural': 'Fitness and Wearables'},
        ),
        migrations.AlterModelOptions(
            name='fitnessdescriptionmodel',
            options={'verbose_name': 'Fitness Description Model', 'verbose_name_plural': 'Fitness Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='fitnessspecificaionmodel',
            options={'verbose_name': 'Fitness Specification Model', 'verbose_name_plural': 'Fitness Specifications'},
        ),
        migrations.AlterModelOptions(
            name='watachandaccessories',
            options={'verbose_name': 'Watch And Accessories', 'verbose_name_plural': 'Watch And Accessories'},
        ),
    ]
