# Generated by Django 4.2.6 on 2024-04-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_and_wearable', '0008_alter_fitness_and_wearable_product_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness_and_wearable_product',
            name='FitnessDescriptionModel',
        ),
    ]
