# Generated by Django 4.2.6 on 2024-03-24 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_and_accessories', '0002_productbrand_cableandinternconnectproductadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cableandinternconnectproductadd',
            old_name='ipadAndTAB',
            new_name='cableAndinternconnect',
        ),
        migrations.RenameField(
            model_name='cableandinternconnectproductadd',
            old_name='phoneAndtablet',
            new_name='powerAndaccessories',
        ),
    ]
