# Generated by Django 4.2.6 on 2024-04-15 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_and_accessories', '0003_rename_ipadandtab_cableandinternconnectproductadd_cableandinternconnect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cableandinternconnectproductadd',
            name='quentity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
