# Generated by Django 4.2.6 on 2024-04-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('power_and_accessories', '0005_remove_cableandinternconnectproductadd_quentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='powerAndaccessoriesDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phone_and_tablet/media/image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='cableandinternconnectproductadd',
            old_name='productBrand',
            new_name='PowerProductBrand',
        ),
        migrations.RenameModel(
            old_name='productBrand',
            new_name='PowerProductBrand',
        ),
        migrations.CreateModel(
            name='PowerAndaccessoriesSpecificaionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PowerOutput', models.CharField(max_length=350)),
                ('Model', models.CharField(max_length=350)),
                ('Batterycapacity', models.CharField(max_length=350)),
                ('Inputinterface', models.CharField(max_length=350)),
                ('color', models.CharField(max_length=350)),
                ('OtherFeaturesInfo', models.CharField(max_length=350)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='power_and_accessories.powerproductbrand')),
            ],
        ),
        migrations.AddField(
            model_name='cableandinternconnectproductadd',
            name='PowerAndaccessoriesSpecificaionModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='power_and_accessories.powerandaccessoriesspecificaionmodel'),
        ),
        migrations.AddField(
            model_name='cableandinternconnectproductadd',
            name='powerAndaccessoriesDescriptionModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='power_and_accessories.powerandaccessoriesdescriptionmodel'),
        ),
    ]
