# Generated by Django 4.2.6 on 2024-03-23 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loptob_and_desktop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='laptob_and_destop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('product_code', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='conver_and_glass/media/image')),
                ('BusineesClassLoptob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loptob_and_desktop.busineesclassloptob')),
                ('GamingAndLoptob', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loptob_and_desktop.gamingandloptob')),
                ('ImacAndmacMini', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loptob_and_desktop.imacandmacmini')),
                ('Macbook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loptob_and_desktop.macbook')),
                ('ProductBrand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loptob_and_desktop.productbrand')),
                ('ultraBook', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loptob_and_desktop.ultrabook')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
