# Generated by Django 4.2.6 on 2024-03-23 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loptob_and_desktop', '0002_productbrand_laptob_and_destop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laptob_and_destop',
            name='ImacAndmacMini',
        ),
        migrations.DeleteModel(
            name='ImacAndmacMini',
        ),
    ]
