# Generated by Django 4.2.6 on 2024-03-26 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loptob_and_desktop', '0004_alter_laptob_and_destop_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='laptob_and_destop',
            new_name='laptob_and_destop_productAdd',
        ),
    ]
