# Generated by Django 4.2.6 on 2024-04-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loptob_and_desktop', '0007_remove_laptob_and_destop_productadd_quentity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptobDescriptionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='phone_and_tablet/media/image')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LaptobSpecificaionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dimension', models.CharField(max_length=350)),
                ('KeyboardType', models.CharField(max_length=350)),
                ('StorageCapacity', models.CharField(max_length=350)),
                ('StorageType', models.CharField(max_length=350)),
                ('GraphicsModel', models.CharField(max_length=350)),
                ('Model', models.CharField(max_length=350)),
                ('Graphics', models.CharField(max_length=350)),
                ('InterfacePort', models.CharField(max_length=350)),
                ('Weight', models.CharField(max_length=350)),
                ('DisplayType', models.CharField(blank=True, max_length=350, null=True)),
                ('DisplayResulation', models.CharField(blank=True, max_length=350, null=True)),
                ('DisplaySize', models.CharField(max_length=350)),
                ('AdapterType', models.CharField(max_length=350)),
                ('os', models.CharField(max_length=350)),
                ('Chipset', models.CharField(max_length=350)),
                ('Memory', models.CharField(max_length=350)),
                ('Audio', models.CharField(max_length=350)),
                ('BatteryInfo', models.CharField(max_length=350)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loptob_and_desktop.productbrand')),
            ],
        ),
        migrations.AddField(
            model_name='laptob_and_destop_productadd',
            name='LaptobDescriptionModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loptob_and_desktop.laptobdescriptionmodel'),
        ),
        migrations.AddField(
            model_name='laptob_and_destop_productadd',
            name='LaptobSpecificaionModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='loptob_and_desktop.laptobspecificaionmodel'),
        ),
    ]
