# Generated by Django 4.2.6 on 2024-04-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loptob_and_desktop', '0008_laptobdescriptionmodel_laptobspecificaionmodel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptobdescriptionmodel',
            options={'verbose_name': 'Laptob Description Model', 'verbose_name_plural': 'Laptop Descriptions'},
        ),
        migrations.AlterModelOptions(
            name='laptobspecificaionmodel',
            options={'verbose_name': 'Laptob Specificaion Model', 'verbose_name_plural': 'Laptob Specificaions'},
        ),
    ]
