# Generated by Django 4.2.6 on 2024-03-23 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conver_and_glass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverAndGlassProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.CharField(blank=True, max_length=20, null=True)),
                ('image', models.ImageField(upload_to='conver_and_glass/media/image')),
            ],
            options={
                'ordering': ['price'],
            },
        ),
    ]
