# Generated by Django 4.2.6 on 2024-03-23 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conver_and_glass', '0002_coverandglassproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverandglassproduct',
            name='coverAndglass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conver_and_glass.coverandglass'),
        ),
    ]
