# Generated by Django 4.2.6 on 2024-03-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conver_and_glass', '0007_remove_coverandglassproduct_productbrand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverandglassproduct',
            name='productBrand',
            field=models.ManyToManyField(to='conver_and_glass.productbrand'),
        ),
    ]
