# Generated by Django 4.2.6 on 2024-04-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conver_and_glass', '0009_remove_coverandglassproduct_productbrand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverandglassproduct',
            name='quentity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
