# Generated by Django 4.2.6 on 2024-04-22 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conver_and_glass', '0012_remove_coverandglassproduct_quentity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverandglass',
            options={'verbose_name': 'CoverAndglass', 'verbose_name_plural': 'cover and glass '},
        ),
        migrations.AlterModelOptions(
            name='coverandglassproduct',
            options={'ordering': ['price'], 'verbose_name': 'CoverAndGlassProduct', 'verbose_name_plural': 'Cover And Glass Products '},
        ),
        migrations.AlterModelOptions(
            name='productbrandmodel',
            options={'verbose_name': 'productBrandModel', 'verbose_name_plural': 'ProductBrand '},
        ),
    ]
